### ISSUE TITLE
talk about concept

### ISSUE THREAD

**Issue by MCR2601** [boredStudents/The-Jam#1]
Was wollen wir machen?

**Comment by MCR2601** [comment]
das gilt für

**Comment by MCR2601** [comment]
FUUUUUUUUUUUUUUUCK

**Comment by Masaru26** [comment]
Strategiespiel RTS / RB?

**Comment by MCR2601** [comment]
RB

**Comment by MCR2601** [comment]
Divinity original sin

**Comment by MCR2601** [comment]
Civ

**Comment by MCR2601** [comment]
Grid

**Comment by Masaru26** [comment]
Moderne / Zukunft

**Comment by MCR2601** [comment]
- [x] Square Grid
- [ ] Hex Grid
- [ ] Octa Grid
Grid sehr klein

**Comment by MCR2601** [comment]
Wie world Gen

**Comment by MCR2601** [comment]
Grid nur für gebäude und World gen
sonst wie bei divinity

**Comment by Masaru26** [comment]
Verbandssytem für Truppen

**Comment by Masaru26** [comment]
RB Starcraft?

**Comment by Masaru26** [comment]
Koop XCOM

**Comment by MCR2601** [comment]
Alles done passt
