### ISSUE TITLE
Plane Map with grid

### ISSUE THREAD

**Issue by MCR2601** [boredStudents/The-Jam#2]
There should be a plane on the ground and a grid if possible

There should be the possibility for multiple different layers
the grid contains tiles, every tile is passable, not passable or thin air
Every Tile should be told what its neighbor is. (later can be done by script if we want
everything else by self-judgment

**Comment by Masaru26** [comment]
Extrem simples Grid funktioniert schonmal

**Comment by MCR2601** [comment]
- [x] Gid
- [x] Cover
- [x] Traversals
alles fertig

**Comment by MCR2601** [comment]
still TODO:
more efficent search for neighbours
detection of other traversaltypes
Update passability
